In [12]:
import time

start = time.time()
def max_score(N, scores):
    if N == 1:
        return scores[0]
    
    dp = [[0] * 2 for _ in range(N)]
    dp[0][0] = scores[0]  
    dp[0][1] = scores[0] 
    
    if N > 1:
        dp[1][0] = scores[1] 
        dp[1][1] = scores[0] + scores[1] 

    for i in range(2, N):
        dp[i][0] = max(dp[i-2][0], dp[i-2][1]) + scores[i]
        dp[i][1] = dp[i-1][0] + scores[i]

    return max(dp[N-1][0], dp[N-1][1])

# 예제 입력
import random
N = 300
scores = [random.randint(0,100) for _ in range(300)]
print(max_score(N, scores))
print("time : ", time.time()-start)

11052
time :  0.004052400588989258


In [13]:
import numpy as np

# 확률 데이터
p = [0.05, 0.15, 0.05, 0.35, 0.05,0.35]
q = [0, 0, 0, 0, 0, 0,0]
n = len(p)

# e와 w 배열 초기화
e = np.zeros((n+2, n+1))
w = np.zeros((n+2, n+1))

# root 배열 초기화
root = np.zeros((n+1, n+1), dtype=int)

# 초기화 부분
for i in range(1, n+2):
    e[i, i-1] = q[i-1]
    w[i, i-1] = q[i-1]

# 메인 알고리즘
for l in range(1, n+1):
    for i in range(1, n-l+2):
        j = i+l-1
        e[i, j] = float('inf')
        w[i, j] = w[i, j-1] + p[j-1] + q[j]
        for r in range(i, j+1):
            t = e[i, r-1] + e[r+1, j] + w[i, j]
            if t < e[i, j]:
                e[i, j] = t
                root[i, j] = r

# e와 root 테이블의 결과
(e, root,w)


(array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.05, 0.25, 0.35, 0.95, 1.05, 1.8 ],
        [0.  , 0.  , 0.15, 0.25, 0.8 , 0.9 , 1.65],
        [0.  , 0.  , 0.  , 0.05, 0.45, 0.55, 1.3 ],
        [0.  , 0.  , 0.  , 0.  , 0.35, 0.45, 1.2 ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.45],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.35],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]]),
 array([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 2, 4, 4, 4],
        [0, 0, 2, 2, 4, 4, 4],
        [0, 0, 0, 3, 4, 4, 4],
        [0, 0, 0, 0, 4, 4, 4],
        [0, 0, 0, 0, 0, 5, 6],
        [0, 0, 0, 0, 0, 0, 6]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.05, 0.2 , 0.25, 0.6 , 0.65, 1.  ],
        [0.  , 0.  , 0.15, 0.2 , 0.55, 0.6 , 0.95],
        [0.  , 0.  , 0.  , 0.05, 0.4 , 0.45, 0.8 ],
        [0.  , 0.  , 0.  , 0.  , 0.35, 0.4 , 0.75],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.4 ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.35],