In [6]:
def Merge_Sort(A):
    sorted=[]
    left = 0; right = len(A)
    mid = (left+right)//2
    if(right<=1):
        return A
    l = Merge_Sort(A[:mid])
    h = Merge_Sort(A[mid:])
    i = 0; j = 0
    while(i<len(l) and j < len(h)):
        if l[i] < h[j]:
            sorted.append(l[i])
            i += 1
        else:
            sorted.append(h[j])
            j += 1
        print(sorted)
    while i < len(l):
        sorted.append(l[i])
        i+=1
        print(sorted)
    while j < len(h):
        sorted.append(h[j])
        j += 1
        print(sorted)
    return sorted

In [7]:
A = [124,42,354,79,6,240,150,8]
B = Merge_Sort(A)
B

[42]
[42, 124]
[79]
[79, 354]
[42]
[42, 79]
[42, 79, 124]
[42, 79, 124, 354]
[6]
[6, 240]
[8]
[8, 150]
[6]
[6, 8]
[6, 8, 150]
[6, 8, 150, 240]
[6]
[6, 8]
[6, 8, 42]
[6, 8, 42, 79]
[6, 8, 42, 79, 124]
[6, 8, 42, 79, 124, 150]
[6, 8, 42, 79, 124, 150, 240]
[6, 8, 42, 79, 124, 150, 240, 354]


[6, 8, 42, 79, 124, 150, 240, 354]

In [7]:
def mergeSort(array):
    if len(array) > 1:  

        #  r is the point where the array is divided into two subarrays
        r = len(array)//2
        L = array[:r]
        M = array[r:]

        # Sort the two halves
        mergeSort(L)
        mergeSort(M)

        i = j = k = 0

        # Until we reach either end of either L or M, pick larger among
        # elements L and M and place them in the correct position at A[p..r]
        while i < len(L) and j < len(M):
            if L[i] < M[j]:
                array[k] = L[i]
                i += 1
            else:
                array[k] = M[j]
                j += 1
            k += 1
            print(array)
        # When we run out of elements in either L or M,
        # pick up the remaining elements and put in A[p..r]
        while i < len(L):
            array[k] = L[i]
            i += 1
            k += 1
            print(array)

        while j < len(M):
            array[k] = M[j]
            j += 1
            k += 1
            print(array)


# Print the array
def printList(array):
    for i in range(len(array)):
        print(array[i], end=" ")
    print()


# Driver program
if __name__ == '__main__':
    array = [6, 5, 12, 10, 9, 1]

    mergeSort(array)

    print("Sorted array is: ")
    printList(array)

[5, 12]
[5, 12]
[5, 5, 12]
[5, 6, 12]
[5, 6, 12]
[1, 1]
[1, 9]
[1, 9, 1]
[1, 9, 1]
[1, 9, 10]
[1, 5, 12, 10, 9, 1]
[1, 5, 12, 10, 9, 1]
[1, 5, 6, 10, 9, 1]
[1, 5, 6, 9, 9, 1]
[1, 5, 6, 9, 10, 1]
[1, 5, 6, 9, 10, 12]
Sorted array is: 
1 5 6 9 10 12 


In [24]:
import math
print(4**0.5, math.sqrt(4), math.pow(4,0.5),pow(4,0.5))

2.0 2.0 2.0 2.0


In [2]:
import numpy as np
from statsmodels.tsa.vector_ar.vecm import coint_johansen

# 예시 데이터: 여기서는 무작위 데이터를 생성합니다. 실제 데이터로 대체해야 합니다.
np.random.seed(10)
data = np.random.randn(100, 3)  # 100개의 관측값과 3개의 시계열 변수를 가진 데이터

# 요한슨 검정 수행
result = coint_johansen(data, det_order=0, k_ar_diff=1)


# 고유값
print("고유값:", result.eig)

# 공적분 벡터
print("공적분 벡터:\n", result.evec)

# 검정 통계량
print("추적 검정 통계량:", result.lr1)  # 추적 검정 통계량
print("최대 고유값 검정 통계량:", result.lr2)  # 최대 고유값 검정 통계량


고유값: [0.45084583 0.36200304 0.30331959]
공적분 벡터:
 [[ 0.30930243 -1.57182939  0.20001606]
 [-0.73416188 -0.60473    -1.23381376]
 [-1.39442781  0.18152321  0.61795972]]
추적 검정 통계량: [138.20217811  79.46332499  35.41999196]
최대 고유값 검정 통계량: [58.73885312 44.04333303 35.41999196]


In [5]:
data

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737],
       [-0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489, -1.97772828],
       [-1.7433723 ,  0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221,  0.09914922],
       [ 1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 ],
       [-0.47614201,  1.30847308,  0.19501328],
       [ 0.40020999, -0.33763234,  1.25647226],
       [-0.7319695 ,  0.66023155, -0.35087189],
       [-0.93943336, -0.48933722, -0.80459114],
       [-0.21269764, -0.33914025,  0.31216994],
       [ 0.56515267, -0.14742026, -0.02590534],
       [ 0.2890942 , -0.53987907,  0.70816002],
       [ 0.84222474,  0.2035808 ,  2.39470366],
       [ 0.91745894, -0.11227247, -0.36218045],
       [-0.23218226, -0.5017289 ,  1.128